name: main

on:
  push:
    branches:
      - master
      
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Checkout dependencies
      uses: actions/checkout@v2
      with:
        repository: ${{ secrets.LibsRepository }}
        token: ${{ secrets.LibsRepositoryToken }}
        path: 3rdparty/ml

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore -c Release
